# Mailjet API Configuration
mailjet.api.key=c264248220222ce06c44f5eef056451c
mailjet.secret.key=b2fcbe19d1f63b0e4ac71ca825cdb118
mailjet.from.email=ghofranehraghui@gmail.com
mailjet.from.name=Unimind - Sant\uFFFD Mentale

# Utilisez la cl\u00E9 qui fonctionne dans FlutterFlow
gemini.api.key=

