# Clé API Google Gemini pour la génération d'événements
# clé : https://aistudio.google.com/app/apikey
gemini.api.key=AIzaSyCsYlTLuiEMhfbKW9lAmZzKCKXtYceL4mc
gemini.model=gemini-2.5-flash

# Configuration email SMTP (Gmail)
# Utiliser un App Password Gmail : https://myaccount.google.com/apppasswords
mail.username=nadineeddouch07@gmail.com
mail.password=jttd apnv wxpj rxlt
