# Cl\u00C3\u00A9 API Google Gemini pour la g\u00C3\u00A9n\u00C3\u00A9ration d'\u00C3\u00A9v\u00C3\u00A9nements
# cl\u00C3\u00A9 : https://aistudio.google.com/app/apikey
gemini.api.key=AIzaSyBMosH01WhSkhKSbnweO6GQwBB1J8IrMpw
gemini.model=gemini-2.5-flash

# Configuration email SMTP (Gmail)
# Utiliser un App Password Gmail : https://myaccount.google.com/apppasswords
mail.username=nadineeddouch07@gmail.com
mail.password=jttd apnv wxpj rxlt
